# Generated by Django 4.1.4 on 2023-02-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(null=True, to='statistika.businesstype'),
        ),
    ]
