# Generated by Django 4.1.4 on 2023-02-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0003_company_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(to='statistika.businesstype'),
        ),
    ]
