# Generated by Django 4.1.4 on 2023-03-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0004_alter_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='often',
            field=models.CharField(blank=True, choices=[('30', '30'), ('7', '7')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(blank=True, choices=[('Added', 'Added'), ('Stopped', 'Stopped'), ('Deleted', 'Deleted')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='often',
            field=models.CharField(blank=True, choices=[('30', '30'), ('7', '7')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='status',
            field=models.CharField(blank=True, choices=[('Added', 'Added'), ('Stopped', 'Stopped'), ('Deleted', 'Deleted')], max_length=25, null=True),
        ),
    ]
