# Generated by Django 4.2 on 2023-05-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0006_expense_next_pay_income_next_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(null=True, to='statistika.businesstype'),
        ),
    ]
