# Generated by Django 4.2 on 2023-05-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0007_alter_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.ManyToManyField(to='statistika.businesstype'),
        ),
    ]
