# Generated by Django 4.2 on 2023-05-05 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistika', '0008_alter_company_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
